language: node_js
node_js:
  - 10
env:
  global:
    - PRODUCTION_HTTPS_PORT=443
    - HTTPS_PORT=8081
    - HTTP_PORT=80
branches:
  only:
    - development
install: true
script: true
addons:
  ssh_known_hosts:
    - 167.71.155.136
before_install:
  - openssl aes-256-cbc -K $encrypted_a6e4ebc3e70e_key -iv $encrypted_a6e4ebc3e70e_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
  - chmod 600 ~/.ssh/id_rsa
  - ssh root@167.71.155.136 -o StrictHostKeyChecking=no 'npm install -g pm2 && cd ~/code/tradingview-alert && git pull origin development && chmod +x deploy.sh && ./deploy.sh && npm install && npm run production'
